// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/deserialization/src/builtins.proto

package kotlin.reflect.jvm.internal.impl.serialization.builtins;

public final class BuiltInsProtoBuf {
  private BuiltInsProtoBuf() {}
  public static void registerAllExtensions(
      kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite registry) {
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.packageFqName);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.classAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.constructorAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.functionAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.propertyAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.compileTimeValue);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.enumEntryAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.parameterAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.typeAnnotation);
    registry.add(kotlin.reflect.jvm.internal.impl.serialization.builtins.BuiltInsProtoBuf.typeParameterAnnotation);
  }
  public static final int PACKAGE_FQ_NAME_FIELD_NUMBER = 151;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Package { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package,
      java.lang.Integer> packageFqName = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Package.getDefaultInstance(),
        0,
        null,
        null,
        151,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.INT32,
        java.lang.Integer.class);
  public static final int CLASS_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Class { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> classAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Class.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int CONSTRUCTOR_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Constructor { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Constructor,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> constructorAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Constructor.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int FUNCTION_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Function { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Function,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> functionAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Function.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int PROPERTY_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Property { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Property,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> propertyAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Property.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int COMPILE_TIME_VALUE_FIELD_NUMBER = 151;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Property { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Property,
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.Argument.Value> compileTimeValue = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Property.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.Argument.Value.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.Argument.Value.getDefaultInstance(),
        null,
        151,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.Argument.Value.class);
  public static final int ENUM_ENTRY_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.EnumEntry { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.EnumEntry,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> enumEntryAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.EnumEntry.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int PARAMETER_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.ValueParameter { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.ValueParameter,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> parameterAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.ValueParameter.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int TYPE_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.Type { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Type,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> typeAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Type.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);
  public static final int TYPE_PARAMETER_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .kotlin.reflect.jvm.internal.impl.serialization.TypeParameter { ... }</code>
   */
  public static final
    kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<
      kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.TypeParameter,
      java.util.List<kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation>> typeParameterAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite
          .newRepeatedGeneratedExtension(
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.TypeParameter.getDefaultInstance(),
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.getDefaultInstance(),
        null,
        150,
        kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE,
        false,
        kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf.Annotation.class);

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}